#!/usr/bin/env python3
import argparse
import logging
import sys
from pathlib import Path

from . import __version__
from .config import load_config
from .generator import Generator
from .utils import get_example_templates_path, ensure_directories

logging.basicConfig(
    level=logging.INFO,
    format='%(levelname)s: %(message)s'
)
logger = logging.getLogger(__name__)


def cmd_generate(args):
    """Handle 'generate' command."""
    config_path = args.config
    try:
        config = load_config(config_path)
    except Exception as e:
        logger.error(f"Failed to load config: {e}")
        return 1

    if config_path is None:
        config_path = ".sommelier/schema.yaml"
        config_dir = Path.cwd()
    else:
        config_dir = Path(config_path).parent

    template_dir_str = config.get('template_dir', '.sommelier/tmplts')
    template_dir = config_dir / template_dir_str if not Path(template_dir_str).is_absolute() else template_dir_str

    try:
        gen = Generator(str(template_dir))
    except Exception as e:
        logger.error(f"Failed to initialize generator: {e}")
        return 1

    if args.output_dir:
        for job_name, job in config.get('jobs', {}).items():
            job['output'] = str(Path(args.output_dir) / Path(job['output']).name)

    successful = gen.generate_all(config, dry_run=args.dry_run)
    total = len(config.get('jobs', {}))

    if args.dry_run:
        logger.info(f"Dry run complete: {successful}/{total} job(s) ready")
    else:
        logger.info(f"Generation complete: {successful}/{total} file(s) created")

    return 0 if successful == total else 1


def cmd_init(args):
    """Handle 'init' command."""
    output_dir = args.output or '.'

    try:
        output_path = Path(output_dir)

        sommelier_dir = output_path / '.sommelier'
        ensure_directories(sommelier_dir)

        tmplts_dir = sommelier_dir / 'tmplts'
        ensure_directories(tmplts_dir)

        schema_path = sommelier_dir / 'schema.yaml'
        default_schema = """# Sommelier Configuration
# Generated by: sommelier init
#
# This is your project's data model and code generation configuration.
# Define your data model once, generate code in multiple languages.

# Default template directory is .sommelier/tmplts/
# Override with template_dir if needed (relative to this file)

# Jobs are defined as a map, where each key is a job name.
# Each job has:
#   - template: Either a template filename or inline Jinja2 template
#   - output: Path where the generated file will be written
#   - context: Dictionary of variables passed to the template

jobs: {}
  # Example job:
  # my_entity:
  #   template: entity.java.j2
  #   output: generated/Entity.java
  #   context:
  #     entity_name: User
  #     fields:
  #       - name: id
  #         type: Long
  #
  # Or with inline template:
  # my_file:
  #   template: |
  #     # Generated file for {{ name }}
  #     class {{ name }} { }
  #   output: generated/{{ name }}.java
  #   context:
  #     name: User
"""
        with open(schema_path, 'w') as f:
            f.write(default_schema)
        logger.info(f"Created: {schema_path}")

        logger.info(f"Initialized project structure in: {output_path}")
        logger.info(f"Created .sommelier/ directory")
        logger.info(f"Created .sommelier/schema.yaml (default configuration)")
        logger.info(f"Created .sommelier/tmplts/ (template directory)")
        logger.info(f"Next: edit .sommelier/schema.yaml and add your jobs")
        logger.info(f"Then run: sommelier generate")
        return 0

    except Exception as e:
        logger.error(f"Failed to initialize project: {e}")
        return 1


def cmd_list(args):
    """Handle 'list' command."""
    examples_dir = get_example_templates_path()

    if not examples_dir.exists():
        logger.error(f"Examples directory not found: {examples_dir}")
        return 1

    templates = [d.name for d in examples_dir.iterdir() if d.is_dir()]
    templates.sort()

    print("Available templates:")
    for template in templates:
        print(f"  - {template}")

    return 0


def main():
    """Main CLI entry point."""
    parser = argparse.ArgumentParser(
        description='Language-agnostic boilerplate generator from YAML data models and Jinja2 templates',
        prog='sommelier'
    )

    parser.add_argument('--version', action='version', version=f'%(prog)s {__version__}')
    parser.add_argument('--verbose', '-v', action='store_true', help='Enable verbose logging')

    subparsers = parser.add_subparsers(dest='command', help='Available commands')

    # generate command
    gen_parser = subparsers.add_parser('generate', help='Generate boilerplate from schema')
    gen_parser.add_argument('config', nargs='?', default=None, help='Path to schema file (default: .sommelier/schema.yaml)')
    gen_parser.add_argument('--dry-run', action='store_true', help='Show what would be generated without writing')
    gen_parser.add_argument('--output-dir', help='Override output directory for all jobs')
    gen_parser.set_defaults(func=cmd_generate)

    # init command
    init_parser = subparsers.add_parser('init', help='Initialize new project')
    init_parser.add_argument('--output', '-o', help='Output directory (default: current)')
    init_parser.set_defaults(func=cmd_init)

    # list command
    list_parser = subparsers.add_parser('list', help='List available templates')
    list_parser.set_defaults(func=cmd_list)

    args = parser.parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    if not hasattr(args, 'func'):
        parser.print_help()
        return 0

    try:
        return args.func(args)
    except Exception as e:
        logger.error(f"Unexpected error: {e}")
        return 1


if __name__ == '__main__':
    sys.exit(main())
