#!/usr/bin/env python3
import argparse
import fnmatch
import logging
import sys
from pathlib import Path

try:
    from . import __version__
    from .config import load_config
    from .generator import Generator
    from .utils import get_example_templates_path, ensure_directories
except ImportError:
    sys.path.insert(0, str(Path(__file__).parent.parent))
    from pati import __version__
    from pati.config import load_config
    from pati.generator import Generator
    from pati.utils import get_example_templates_path, ensure_directories

logging.basicConfig(
    level=logging.INFO,
    format='%(levelname)s: %(message)s'
)
logger = logging.getLogger(__name__)


def cmd_generate(args):
    """Handle 'generate' command."""
    config_path = args.config or ".pati/schema.yaml"
    try:
        config = load_config(config_path)
    except Exception as e:
        logger.error(f"Failed to load config: {e}")
        return 1

    config_dir = Path(config_path).parent

    template_dir_str = config.get('template_dir', 'tmplts')
    template_dir = config_dir / template_dir_str if not Path(template_dir_str).is_absolute() else template_dir_str

    try:
        gen = Generator(str(template_dir), config)
    except Exception as e:
        logger.error(f"Failed to initialize generator: {e}")
        return 1

    all_jobs = config.get('jobs', {})

    if args.jobs:
        patterns = args.jobs
        selected = {
            name: job for name, job in all_jobs.items()
            if any(fnmatch.fnmatch(name, p) for p in patterns)
        }
        unmatched = [p for p in patterns if not any(fnmatch.fnmatch(n, p) for n in all_jobs)]
        for p in unmatched:
            logger.warning(f"No jobs matched pattern: {p}")
        config = dict(config, jobs=selected)

    if args.output_dir:
        for job_name, job in config.get('jobs', {}).items():
            job['output'] = str(Path(args.output_dir) / Path(job['output']).name)

    successful = gen.generate_all(config, dry_run=args.dry_run)
    total = len(config.get('jobs', {}))

    if args.dry_run:
        logger.info(f"Dry run complete: {successful}/{total} job(s) ready")
    else:
        logger.info(f"Generation complete: {successful}/{total} file(s) created")

    return 0 if successful == total else 1


def cmd_init(args):
    """Handle 'init' command."""
    output_dir = args.output or '.'

    try:
        output_path = Path(output_dir)

        pati_dir = output_path / '.pati'
        ensure_directories(str(pati_dir))

        tmplts_dir = pati_dir / 'tmplts'
        ensure_directories(str(tmplts_dir))

        # Check and warn about existing schema.yaml
        schema_path = pati_dir / 'schema.yaml'
        if schema_path.exists():
            logger.warning(f"File already exists: {schema_path}")
            logger.warning(f"Skipping (remove file if you need a pristine version)")
        else:
            default_schema = """# pati Configuration
# Generated by: pati init
#
# This is your project's data model and code generation configuration.
# Define your data model once, generate code in multiple languages.

# Default template directory is .pati/tmplts/
# Override with template_dir if needed (relative to this file)

# Jobs are defined as a map, where each key is a job name.
# Each job has:
#   - template: Either a template filename or inline Jinja2 template
#   - output: Path where the generated file will be written
#   - context: Dictionary of variables passed to the template
#
# Context field values can contain Jinja2 templates that reference other fields,
# enabling reusable, hierarchical configuration:

jobs: {}
  # Example 1: Template file reference
  # my_entity:
  #   template: entity.java.j2
  #   output: generated/Entity.java
  #   context:
  #     entity_name: User
  #     fields:
  #       - name: id
  #         type: Long

  # Example 2: Inline template
  # my_file:
  #   template: |
  #     class {{ entity_name }} { }
  #   output: generated/{{ entity_name }}.java
  #   context:
  #     entity_name: User

  # Example 3: Context field templates (resolved before template rendering)
  # app_config:
  #   template: config.properties.j2
  #   output: generated/config.properties
  #   context:
  #     company: acme
  #     domain: "{{ company }}.com"          # resolved to: acme.com
  #     service_package: "{{ domain }}.services"  # resolved to: acme.com.services
"""
            with open(schema_path, 'w') as f:
                f.write(default_schema)
            logger.info(f"Created: {schema_path}")

        # Copy sample templates from bundled examples
        examples_dir = get_example_templates_path()
        if examples_dir.exists():
            # Get all template files from all examples
            template_files_copied = 0
            for example_dir in examples_dir.iterdir():
                if not example_dir.is_dir():
                    continue
                templates_src = example_dir / 'templates'
                if not templates_src.exists():
                    continue

                for template_file in templates_src.glob('*'):
                    if not template_file.is_file():
                        continue

                    dst = tmplts_dir / template_file.name
                    if dst.exists():
                        logger.warning(f"Template already exists: {dst}")
                        logger.warning(f"Skipping (remove file if you need to reinitialize)")
                    else:
                        with open(template_file) as src, open(dst, 'w') as dstf:
                            dstf.write(src.read())
                        logger.info(f"Copied: {dst.name}")
                        template_files_copied += 1

            if template_files_copied > 0:
                logger.info(f"Copied {template_files_copied} template file(s) from examples")

        logger.info(f"")
        logger.info(f"Initialized project structure in: {output_path}")
        logger.info(f"Created .pati/ directory")
        logger.info(f"Created .pati/schema.yaml (configuration)")
        logger.info(f"Created .pati/tmplts/ (template directory with sample templates)")
        logger.info(f"")
        logger.info(f"Next steps:")
        logger.info(f"1. Edit .pati/schema.yaml to define your jobs")
        logger.info(f"2. Customize templates in .pati/tmplts/ as needed")
        logger.info(f"3. Run: pati generate")
        return 0

    except Exception as e:
        logger.error(f"Failed to initialize project: {e}")
        return 1


def cmd_list(args):
    """Handle 'list' command."""
    examples_dir = get_example_templates_path()

    if not examples_dir.exists():
        logger.error(f"Examples directory not found: {examples_dir}")
        return 1

    templates = [d.name for d in examples_dir.iterdir() if d.is_dir()]
    templates.sort()

    print("Available templates:")
    for template in templates:
        print(f"  - {template}")

    return 0


def main():
    """Main CLI entry point."""
    parser = argparse.ArgumentParser(
        description='Language-agnostic boilerplate generator from YAML data models and Jinja2 templates',
        prog='pati'
    )

    parser.add_argument('--version', '-v', action='version', version=f'%(prog)s {__version__}')
    level_group = parser.add_mutually_exclusive_group()
    level_group.add_argument('--verbose', action='store_true', help='Enable verbose/debug logging')
    level_group.add_argument('--quiet', '-q', action='store_true', help='Print only warnings and errors')
    level_group.add_argument('--silent', '-s', action='store_true', help='Print only errors')

    subparsers = parser.add_subparsers(dest='command', help='Available commands')

    # generate command
    gen_parser = subparsers.add_parser('generate', help='Generate boilerplate from schema')
    gen_parser.add_argument('--config', '-c', nargs='?', default=None,
                            help='Path to schema file (default: .pati/schema.yaml)')
    gen_parser.add_argument('jobs', nargs='*', metavar='JOB',
                            help='Job name(s) or glob patterns to run (default: all jobs)')
    gen_parser.add_argument('--dry-run', action='store_true', help='Show what would be generated without writing')
    gen_parser.add_argument('--output-dir', help='Override output directory for all jobs')
    gen_parser.set_defaults(func=cmd_generate)

    # init command
    init_parser = subparsers.add_parser('init', help='Initialize new project')
    init_parser.add_argument('--output', '-o', help='Output directory (default: current)')
    init_parser.set_defaults(func=cmd_init)

    # list command
    list_parser = subparsers.add_parser('list', help='List available templates')
    list_parser.set_defaults(func=cmd_list)

    args = parser.parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)
    elif args.quiet:
        logging.getLogger().setLevel(logging.WARNING)
    elif args.silent:
        logging.getLogger().setLevel(logging.ERROR)

    if not hasattr(args, 'func'):
        parser.print_help()
        return 0

    try:
        return args.func(args)
    except Exception as e:
        logger.error(f"Unexpected error: {e}")
        return 1


if __name__ == '__main__':
    sys.exit(main())
